#!/usr/bin/python

import argparse
import errno
import os
import sys

# pip install --user pillow
from PIL import Image

def save_rotated_image(degree):
	src = Image.open(args.srcimg)
	rotated = src.rotate(-degree)

	name = "{:03d}".format(degree)
	fullpath = out + "/" + name + ".png"

	if args.bgimg:
		bg = Image.open(args.bgimg)

		# get alpha mask from source image
		alpha = src.getchannel('A')

		composite = Image.composite(rotated, bg, alpha)
		composite.save(fullpath)
	else:
		rotated.save(fullpath)

	print(fullpath + " created")

parser = argparse.ArgumentParser()
parser.add_argument("--bgimg", help="background image")
parser.add_argument("srcimg", help="source image to rotate")
parser.add_argument("outdir", help="output directory to save rotated images")
args = parser.parse_args()

out = args.outdir

if not os.path.exists(out):
	os.mkdir(out)
elif not os.path.isdir(out):
	raise Exception(out + " is exist, but it is not a directory")

for degree in range(360):
	save_rotated_image(degree)
